version: "3"

services:
  api:
    build:
      context: ./api
    ports:
      - "9001:9001"
    volumes:
      - /app/node_modules
      - ./api:/app
    environment:
      - NODE_ENV=development
      - PORT=9001
  fo:
    build:
      context: ./fo
    ports:
      - "8080:8080"
    volumes:
      - /app/node_modules
      - /app/src/styles
      - ./fo:/app
    environment:
      - NODE_ENV=development
